INSERT INTO settings (`key`, `value`) VALUES
  ('site_name',              'Mon Site'),
  ('site_tagline',           ''),
  ('site_description',       'Site vitrine professionnel.'),
  ('site_logo_path',         ''),
  ('site_favicon_path',      ''),
  ('color_primary',          '#1e40af'),
  ('color_secondary',        '#64748b'),
  ('color_accent',           '#f59e0b'),
  ('contact_address',        ''),
  ('contact_city',           ''),
  ('contact_postal_code',    ''),
  ('contact_country',        'FR'),
  ('contact_phone',          ''),
  ('contact_email',          ''),
  ('contact_hours',          ''),
  ('social_facebook',        ''),
  ('social_instagram',       ''),
  ('social_linkedin',        ''),
  ('social_twitter',         ''),
  ('social_youtube',         ''),
  ('seo_default_title',      'Mon Site'),
  ('seo_default_description',''),
  ('seo_og_image',           ''),
  ('seo_keywords',           ''),
  ('localbusiness_type',     'LocalBusiness'),
  ('localbusiness_geo_lat',  ''),
  ('localbusiness_geo_lng',  ''),
  ('analytics_provider',     'none'),
  ('analytics_ga4_id',       ''),
  ('analytics_gtm_id',       ''),
  ('analytics_plausible_domain',''),
  ('analytics_matomo_url',   ''),
  ('analytics_matomo_site_id',''),
  ('consent_banner_enabled', '0')
ON DUPLICATE KEY UPDATE `value` = VALUES(`value`);
