CREATE TABLE equipe (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    nom VARCHAR(190) NOT NULL,
    fonction VARCHAR(190) NULL,
    photo VARCHAR(255) NULL,
    bio TEXT NULL,
    linkedin VARCHAR(255) NULL,
    ordre SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    published TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_published_ordre (published, ordre)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
